# Site settings
title: Zero Tolerance
tag_text: Zero Tolerance
description: Zero Tolerance Against Sexual Harassment in India
#url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
